### Get all persons
GET http://localhost:3001/api/persons

### Get person 
GET http://localhost:3001/api/persons/3

### Delete person 
DELETE http://localhost:3001/api/persons/3


### Create person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"LA MAMBA LOCA",
    "number":"000-0000-0000"
}
